### ISSUE TITLE
Aseprite RPC Not working

### ISSUE THREAD

**Issue by TheStupidOneHere** [vanishedvan/aseprite-rich-presence#5]
Hey! I know this is an old repo but I just wanted to have that sort of RPC you guys made instead of the plain one that's in aseprite by default
I may just be doing something wrong here but I've really tried everything
Command: "node index.js"
```
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: D:\games\Aseprite.v1.2.21\RPC\aseprite-rich-presence-master\config.json: Unexpected token g in JSON at position 18
    at parse (<anonymous>)
←[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (D:\games\Aseprite.v1.2.21\RPC\aseprite-rich-presence-master\path.js:4:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
```
I'm not the best at js so I barely understand any of this, any amount of help would be huge
Thanks

**Comment by ibrahimcaj** [comment]
Hello there! Can you send your config.json file contents here?

**Comment by TheStupidOneHere** [comment]
Ofcourse!
```
{
    "path": "D:\games\Aseprite\Aseprite.exe",
    "clientID": "732308035661201542"
}
```

**Comment by TheStupidOneHere** [comment]
Ofc
```
{
    "path": "D:\games\Aseprite\Aseprite.exe",
    "clientID": "732308035661201542"
}
```

**Comment by ibrahimcaj** [comment]
You must use a double backslash instead of a single one.

```
{
    "path": "D:\\games\\Aseprite\\Aseprite.exe",
    "clientID": "732308035661201542"
}
```

**Comment by TheStupidOneHere** [comment]
Ohhh thanks a lot, sorry for the stupid question, I shouldve seen that before
Thanks again! Have a good day
